### ISSUE TITLE
Rails 6 and webpacker scope causing reference errors

### ISSUE THREAD

**Issue by nhaglind** [jeanpaulsio/action-cable-signaling-server#11]
In Rails 6 webpacker wraps the included js now in a limited score function and isn't accessible outside causing reference errors. Your discussion of the problem is exactly what I'm trying to solve, spinning up a rails server, but allowing users to broadcast publically audio only to even nonusers and this looked like a great solution just needs to be updated.

```
(function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _babel_runtime_regenerator__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @babel/runtime/regenerator */ "./node_modules/@babel/runtime/regenerator/index.js");
/* harmony import */ var _babel_runtime_regenerator__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_babel_runtime_regenerator__WEBPACK_IMPORTED_MODULE_0__);


var handleJoinSession = function handleJoinSession() {
  return _babel_runtime_regenerator__WEBPACK_IMPORTED_MODULE_0___default.a.async(function handleJoinSession$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          _context.next = 2;
          return _babel_runtime_regenerator__WEBPACK_IMPORTED_MODULE_0___default.a.awrap(App.cable.subscriptions.create("SessionChannel", {
            connected: function connected() {
              broadcastData({
                type: "initiateConnection"
              });
            },
            received: function received(data) {
              console.log("RECEIVED:", data);
            }
          }));

        case 2:
          App.session = _context.sent;

        case 3:
        case "end":
          return _context.stop();
      }
    }
  });
};
```

```
Uncaught ReferenceError: handleJoinSession is not defined
    at HTMLButtonElement.onclick
```

**Comment by jeanpaulsio** [comment]
Interesting, thanks for writing up this ticket. I'm going to try and take a look at how this might be fixed

**Comment by HarlemSquirrel** [comment]
I was able to get a bit farther where video plays in the window from my camera by adding this to the end of signaling-server.js

```js
export default handleJoinSession()
```

Now I have 

```
ReferenceError: App is not defined
```

I'm very much an ActionCable and WebRTC n00b so I'm not sure what's going on but it looks like maybe things have changed quite a bit in Rails 6.
https://edgeguides.rubyonrails.org/action_cable_overview.html#client-server-interactions-subscriptions

**Comment by jeanpaulsio** [comment]
@nhaglind @HarlemSquirrel - I just updated this repo to support webpacker. Check out the example in the readme

```
Uncaught ReferenceError: handleJoinSession is not defined
    at HTMLButtonElement.onclick
```

The reason for this error is because we can no longer rely on the asset pipeline putting that function in scope. You might do something like this to add the onclick handler

```
// Add event listener's to buttons
document.addEventListener("DOMContentLoaded", () => {
  const joinButton = document.getElementById("join-button");
  const leaveButton = document.getElementById("leave-button");

  joinButton.onclick = handleJoinSession;
  leaveButton.onclick = handleLeaveSession;
});
```

And then in your html.erb file, you would have

```
<button id="join-button">
  Join Room
</button>

<button id="leave-button">
  Leave Room
</button>
```

---

```
ReferenceError: App is not defined
```

`App` not being defined here is a symptom of the same issue in that we no longer have it in scope due to Webpacker usage. These files live in a different directory now, but you would do something like this

```
import consumer from "./channels/consumer";

// more stuff

  consumer.subscriptions.create("SessionChannel", {
    connected: () => {
      broadcastData({
        type: JOIN_ROOM,
        from: currentUser,
      });
    },

// etc
```

Let me know if you need any help setting up!

**Comment by jeanpaulsio** [comment]
I'm going to close this ticket but feel free to continue the discussion

**Comment by nhaglind** [comment]
Thanks for fix! I ended up at the time working around tokbox's api to get the desired result but I'm sure your update will help someone else down the road (and I might come back to do a refactor with this).

**Comment by angelica-karen** [comment]
Hi, I had been hanging on this topic for a while now and this really got me stoked since I am a newbie currently working on a Fiverr clone and going through the entire tutorial, we were taught to use Action Cable for chat but not for a web chat. 

I'm using Rails 6 and encountered the same problems such as uncaught reference error on clicking both the buttons for handleJoinSession and  handleLeaveSession. Before, I used to just add require("packs/signaling-server") in the application.js and the web camera would work but then again, clicking the buttons would yield errors. 

Fast forward, I moved the signaling-server.js under the javascript folder and copy-pasted your solution.  Now, I add require("../signaling-server").  Automatically, without clicking any buttons, the camera would turn on and error will say "Uncaught TypeError: Cannot set property 'onclick' of null" and when I click both the buttons calling the handleJoinSession and handleLeaveSession, I get similar problems as I had prior to the code alteration of signaling-server.js

Appreciate any help. Whether a link to a tutorial or anything that would make this Rails 6 + Webpacker + Action Cable work out. :)
